### ISSUE TITLE
Canada data incorrect

### ISSUE THREAD

**Issue by JanieHuang** [jakobzhao/virus#11]
Great job on the map! Love it! It's so far the most visually user friendly map. 

Only current issue is data for Canada. Previously it was showing amount recovered, but now it's showing that no one has recovered. 

John Hopkins reports: 
BC: 3 Recovered
Ontario: 4 Recovered

There is now also a case in Alberta, that also needs to show up.

**Comment by JanieHuang** [comment]
Suggestion for new source:

https://bnonews.com/index.php/2020/02/the-latest-coronavirus-cases/

**Comment by jakobzhao** [comment]
Thank you so much. Find a good source is hard. and we find that the official sources usually have some time lag.
