### ISSUE TITLE
Graph of active cases

### ISSUE THREAD

**Issue by laurentlb** [jakobzhao/virus#13]
It would be useful to plot the graph of active cases (`confirmed - recovered - death`, I assume).

**Comment by jakobzhao** [comment]
Yes, you are right.. it is a legacy to have the "suspected" ones.

**Comment by jakobzhao** [comment]
Yes, you are right!

**Comment by airguru** [comment]
Please see #15 . 

I am not sure if it's visually important to also plot it.

**Comment by laurentlb** [comment]
Thanks a lot!

I think it's interesting to see it because it reflects the current state. For example, people might wonder if there are there still a lot of active cases in China, or if it's over. Seeing the evolution of that number shows if a country manages to keep things under control (number of active cases is not growing) or if they managed to reverse the trend.

**Comment by airguru** [comment]
Well, assuming that number of deaths is sufficiently small, the "active" is basically confirmed - recovered, which is a value that can still be directly read from the plot (as if it was stacked plot). But If people here will support the plot, It's a matter of 10 minutes to add it to my pull request.

To visualise the current state of "keeping things under control", I proposed the "growth factor" in #16 .

**Comment by jakobzhao** [comment]
@airguru thanks for your contribution! It is a very good suggestion. It is just a matter of time to add this function to the current map. I am so busy at the end of the winter quarter.

**Comment by airguru** [comment]
@jakobzhao I am not sure what do you mean. That's why I did it and you can just comment on or accept the pull request...

**Comment by jakobzhao** [comment]
Thanks, just added.
