### ISSUE TITLE
Nassau County, NY confused with Nassau, NY 

### ISSUE THREAD

**Issue by nschiraldi** [jakobzhao/virus#17]
Not sure if the issue occurs anywhere else, but just thought I'd point out the process is mapping some cases that occur in Nassau County, NY to the town of Nassau in Rensselaer County, NY. I'm not sure if I'll have time to dig through the source code to see if I can suggest a fix. 

![image](https://user-images.githubusercontent.com/8190840/76343613-bd7f9580-62d6-11ea-8e8e-397b58cc37b0.png)

**Comment by jakobzhao** [comment]
updated
