### ISSUE TITLE
Card rendering bugs

### ISSUE THREAD

**Issue by stfnio** [jakobzhao/virus#21]
Hi, stumbled upon this bug:

<img width="457" alt="Screenshot 2020-03-11 at 23 38 50" src="https://user-images.githubusercontent.com/14318852/76463134-f2cdd580-63f3-11ea-9ab8-d049eea7b847.png">

I can try to fix it in a PR if it makes sense.

**Comment by schckngs** [comment]
In my browser only the "recovered" and "death" titles show up...makes it look like the red number is number of people recovered.
![Screen Shot 2020-03-12 at 12 22 06 AM](https://user-images.githubusercontent.com/24460473/76484132-b8fece00-63f7-11ea-9b13-de03cafa500c.png)

**Comment by jakobzhao** [comment]
fixed, thanks you all
