### ISSUE TITLE
Sources of data for Greece

### ISSUE THREAD

**Issue by NikolaosAndritsosHNMS** [jakobzhao/virus#25]
Your site is reporting 428 total cases where the official announcement (from Greece's Ministry of Health) mention 331 total cases. The link is a press conference release a couple of hours ago:
https://www.moh.gov.gr/articles/ministry/grafeio-typoy/press-releases/6871-enhmerwsh-diapisteymenwn-syntaktwn-ygeias-apo-ton-ekproswpo-toy-ypoyrgeioy-ygeias-gia-to-neo-koronoio-kathhghth-swthrh-tsiodra-15-3-2020
Please let us know about the sources of the total cases you report, or if this is a mistake. An error is understandable as soon as it is corrected. I believe becoming a source of misinformation is beyond your purposes.

**Comment by jakobzhao** [comment]
Thanks for your concern. We did realize the difference, and your email was well received too. The data source we used are showing it is 428. We have worked hard to make sure the data are accurate.

**Comment by jakobzhao** [comment]
fixed, so we mark this as close
