### ISSUE TITLE
https://hgis.uw.edu/virus/ shows no data

### ISSUE THREAD

**Issue by MRakhmanin** [jakobzhao/virus#31]
Is it everythings ok with data?
https://hgis.uw.edu/virus/ shows no cases at all 
Looks like there are some problems with csv or parsing, isn't it?
![image](https://user-images.githubusercontent.com/39961490/77072388-a7708400-69fe-11ea-958a-301c6aab45ba.png)

**Comment by stackola** [comment]
There's some merge-conflict markup left in https://github.com/jakobzhao/virus/blob/master/assets/virus.csv

**Comment by MRakhmanin** [comment]
Got it, thx
Actually the best map, due to separately plots over each country

**Comment by stackola** [comment]
You should not have closed this issue, it's actually a problem the owner of this repo has to address

**Comment by MRakhmanin** [comment]
Just thought it's already known issue
