### ISSUE TITLE
Extra colored layer on Vietnam

### ISSUE THREAD

**Issue by bruceyang1998** [jakobzhao/virus#40]
![image](https://user-images.githubusercontent.com/9063679/77201139-5b871300-6ac2-11ea-9725-cf8ce90c08f7.png)
After deleting extra layer using Inspect Element: 
![image](https://user-images.githubusercontent.com/9063679/77201180-6fcb1000-6ac2-11ea-9fe3-dbf1cd8fcc3d.png)

**Comment by jakobzhao** [comment]
Thank you, the problem was solved.

**Comment by jakobzhao** [comment]
I will close this issue.
