### ISSUE TITLE
Adjustable dates in report

### ISSUE THREAD

**Issue by dek-odoo** [jakobzhao/virus#45]
First of all, thanks for a great website !

Can we change the dates on the report ?
For example, the following map has dates from Jan 21 to Mar 22, but dates from Jan 21 to Mar 03 is meaningless as there is no data, in addition the curve looks much steep,

![Screenshot from 2020-03-23 10-43-40](https://user-images.githubusercontent.com/10609055/77283983-a340b100-6cf3-11ea-8f17-9c91e9f8b5e9.png)

Can user change the dates from Mar 03 to Mar 23 ?
Or does it require code changes ?

Thank you

**Comment by jakobzhao** [comment]
Thanks, we are aware of this issue, but it seems the zoom function of c3.js does not work, and we have been working on it.

**Comment by dek-odoo** [comment]
Ok, thanks for sharing :+1:
