### ISSUE TITLE
(Practically) duplicate row in virus.csv

### ISSUE THREAD

**Issue by christopher-llop** [jakobzhao/virus#47]
Was there an issue with the most recent data update?  It looks like row 64 and 63 in virus.csv are 82% identical.  As a comparison, rows 63 and 62 are only 15% identical. 

Love this dashboard!

**Comment by christopher-llop** [comment]
Actually, I think what I'm noticing is a duplicate of : https://github.com/jakobzhao/virus/issues/46, just from the data as opposed to from the image.

**Comment by jakobzhao** [comment]
the csv file is keeping update. The raw data is stored in the database
