### ISSUE TITLE
Georgia (state) and Georgia (country) lumped together

### ISSUE THREAD

**Issue by bruceyang1998** [jakobzhao/virus#9]
As of 3/2/2020 there are no confirmed cases in the state of Georgia. However in the latest update all US states were added and it seems that confirmed cases in the country of Georgia are showing up in the state of Georgia too. 

![image](https://user-images.githubusercontent.com/9063679/75657132-886aa780-5c33-11ea-96c9-ae0b14d7cbe4.png)
![image](https://user-images.githubusercontent.com/9063679/75657141-8dc7f200-5c33-11ea-9d2d-f7875518c172.png)

**Comment by jakobzhao** [comment]
thank you, fixed!
